### ISSUE TITLE
rigochain/rweb3 v1.0.12 변경사항에 따른 개발 가이드 문서 업데이트

### ISSUE THREAD

**Issue by kylekwon-rigochain** [rigochain/rigo-sdk-js#32]
- [x] sign transaction에서 chain id 추가 사항 업데이트
- [ ] decode transaction 추가 업데이트
- [x] account 조회 시 response 업데이트
- [ ] build 및 sign 개선사항 업데이트
- [ ] governance params reponse 업데이트
- [x] TrxProto 업데이트(setDoc, withdraw)

**Comment by EokgiLee** [comment]
[개발 가이드 문서 개편#33](https://github.com/rigochain/rigo-sdk-js/issues/33)

개발 가이드 문서 전체 개편으로 인해 해당 이슈는 닫습니다.
